# Makefile for compiling GpuInfo.cu

# Target name
all: vectorAdd 

# How to build the target
vectorAdd: vectorAdd.cu
	nvcc vectorAdd.cu -o vectorAdd

# Optional: clean up executable
clean:
	rm -f vectorAdd
